<a href="https://colab.research.google.com/github/Jesusdat/Algebra-Lineal/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Crear una matriz con numpy
matriz_np = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(matriz_np)
print("Dimensiones:", matriz_np.shape)  # Imprime: (2, 3) -> 2 filas, 3 columnas

[[1 2 3]
 [4 5 6]]
Dimensiones: (2, 3)


In [ ]:
A = [
    [1, 2],
    [3, 4]
]

B = [
    [5, 6],
    [7, 8]
]

# Sumar elemento por elemento
suma = [
    [A[i][j] + B[i][j] for j in range(len(A[0]))]
    for i in range(len(A))
]

print("Suma con listas:")
for fila in suma:
    print(fila)

Suma con listas:
[6, 8]
[10, 12]


In [ ]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# En NumPy se usa el operador + directamente
suma_np = A + B

print("Suma con NumPy:")
print(suma_np)

Suma con NumPy:
[[ 6  8]
 [10 12]]


In [ ]:
A = [
    [1, 2],
    [3, 4]
]

B = [
    [5, 6],
    [7, 8]
]

# Crear matriz resultado llena de ceros (2x2)
producto = [[0, 0], [0, 0]]

# Algoritmo de multiplicación matricial (3 bucles)
for i in range(len(A)):          # Filas de A
    for j in range(len(B[0])):   # Columnas de B
        for k in range(len(B)):  # Filas de B / Columnas de A
            producto[i][j] += A[i][k] * B[k][j]

print("Multiplicación con listas:")
for fila in producto:
    print(fila)

Multiplicación con listas:
[19, 22]
[43, 50]


In [ ]:
import numpy as np

matriz = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Usando el atributo .T o la función np.transpose()
transpuesta_np = matriz.T

print("Transpuesta con NumPy:")
print(transpuesta_np)

Transpuesta con NumPy:
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np

# 1. Definir la matriz de coeficientes (A) y el vector constante (b)
A = np.array([
    [2, 3],
    [4, -1]
])

b = np.array([8, 2])

# 2. Resolver el sistema Ax = b
x = np.linalg.solve(A, b)

# Mostrar resultados
print(f"Solución:")
print(f"x = {x[0]}")  # Resultado: 1.0
print(f"y = {x[1]}")  # Resultado: 2.0

# 3. Comprobación opcional (A @ x debe ser igual a b)
comprobacion = np.allclose(np.dot(A, x), b)
print(f"¿La solución es correcta?: {comprobacion}")

det = np.linalg.det(A)
if det == 0:
    print("El sistema no tiene una solución única.")


Solución:
x = 1.0
y = 2.0
¿La solución es correcta?: True


In [ ]:
import numpy as np

# Matriz A: Columna 1 = Cuarzo [SiO2, Al2O3], Columna 2 = Plagioclasa [SiO2, Al2O3]
A = np.array([
    [1.00, 0.43],  # Proporción de SiO2
    [0.00, 0.37]   # Proporción de Al2O3
])

# Vector b: Análisis químico global de la roca
b = np.array([0.60, 0.20])

# Resolver el sistema Ax = b
x = np.linalg.solve(A, b)

# Convertir a porcentajes
pct_cuarzo = x[0] * 100
pct_plagioclasa = x[1] * 100

print(f"Composición mineral de la roca:")
print(f"- Cuarzo: {pct_cuarzo:.2f}%")
print(f"- Plagioclasa: {pct_plagioclasa:.2f}%")

Composición mineral de la roca:
- Cuarzo: 36.76%
- Plagioclasa: 54.05%
